name: CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read
  packages: write

jobs:
  lint_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug repo layout
        run: |
          pwd
          ls -la
          test -f requirements.txt || { echo "requirements.txt missing"; exit 1; }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -V
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint (non-blocking)
        run: flake8 . || true

      - name: Tests (if present)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests directory"
          fi

  build_push:
    name: Build and Push (GHCR)
    needs: lint_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
